#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Tags.Dashboard.Pages
{
    using System;
    
    #line 2 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 4 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
    using Hangfire.Dashboard.Resources;
    
    #line default
    #line hidden
    
    #line 10 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
    using Hangfire.Storage.Monitoring;
    
    #line default
    #line hidden
    
    #line 11 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
    using Hangfire.Tags;
    
    #line default
    #line hidden
    
    #line 12 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
    using Hangfire.Tags.Dashboard;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
    using Hangfire.Tags.Dashboard.Monitoring;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
    using Hangfire.Tags.Storage;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class TagsJobsPage : TagsRazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\n");














            
            #line 14 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
  
    Layout = new LayoutPage("Tags");

    int.TryParse(Query("from"), out var from);
    int.TryParse(Query("count"), out var perPage);

    var tags = new string[0];
    string state = null;

    var match = Regex.Match(RequestPath, "^/tags/search(/(?<tags>[^/]+))(/(?<state>[^/]+))?");
    if (match.Success)
    {
        tags = match.Groups["tags"].Value.Split(',');
        state = match.Groups["state"].Value;
    }
    Pager pager;

    var tagsListStyle = Options.TagsListStyle;

    var relatedTags = new List<string>();

    JobList<MatchingJobDto> matchingJobs;
    IDictionary<string, int> matchingStates = null;
    using (var tagStorage = new TagsStorage(Storage))
    {
        var monitor = tagStorage.GetMonitoringApi();

        if (tagsListStyle == TagsListStyle.Dropdown && tags.Length == 1)
        {
            relatedTags = monitor.SearchRelatedTags(tags.First()).ToList();
        }

        pager = new Pager(from, perPage, monitor.GetJobCount(tags, state));
        if (pager.TotalPageCount == 0)
        {
            matchingJobs = new JobList<MatchingJobDto>(Enumerable.Empty<KeyValuePair<string, MatchingJobDto>>());
        }
        else
        {
            matchingJobs = monitor.GetMatchingJobs(tags, pager.FromRecord, pager.RecordsPerPage, state);
            matchingStates = monitor.GetJobStateCount(tags);
        }
    }



            
            #line default
            #line hidden
WriteLiteral("\n");


            
            #line 60 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
 if (tagsListStyle == TagsListStyle.Dropdown && tags.Length == 1 && relatedTags.Any())
{

            
            #line default
            #line hidden
WriteLiteral("    <script>\n        function go(tag) {\n            var baseUrl = \"");


            
            #line 64 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                      Write(Url.To("/tags/search/" + tags.First() + ","));

            
            #line default
            #line hidden
WriteLiteral("\";\n            window.location = baseUrl + tag;\n        }\n    </script>\n");


            
            #line 68 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<div class=\"row\">\n    <div class=\"col-md-3\">\n        ");


            
            #line 71 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
   Write(Html.JobsSidebar());

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n    <div class=\"col-md-9\">\n");


            
            #line 74 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
         if (tags.Length == 1)
        {

            
            #line default
            #line hidden
WriteLiteral("            <h1 class=\"page-header\">标签：");


            
            #line 76 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                  Write(tags[0]);

            
            #line default
            #line hidden
WriteLiteral("</h1>\n");


            
            #line 77 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
        }
        else if (tags.Length > 1)
        {

            
            #line default
            #line hidden
WriteLiteral("            <h1 class=\"page-header\">标签：");


            
            #line 80 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                  Write(string.Join(", ", tags));

            
            #line default
            #line hidden
WriteLiteral("</h1>\n");


            
            #line 81 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <h1 class=\"page-header\">标签</h1>\n");


            
            #line 85 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\n");


            
            #line 87 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
         if (tagsListStyle == TagsListStyle.Dropdown && tags.Length == 1 && relatedTags.Any())
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"col-md-12 related-tags\">\n                <datalist id=\"ha" +
"ngfireTagsList\">\n");


            
            #line 91 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                     foreach (var t in relatedTags)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <option value=\"");


            
            #line 93 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                  Write(t);

            
            #line default
            #line hidden
WriteLiteral("\"></option>\n");


            
            #line 94 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral(@"                </datalist>
                <div class=""col-md-10"">
                    <input class=""form-control"" id=""selectedTag"" list=""hangfireTagsList"" autocomplete=""off"" placeholder=""Select a related tag"" />
                </div>
                <div class=""col-md-2"">
                    <button id=""btn_go"" class=""btn"" onclick=""go(document.getElementById('selectedTag').value)"">Go</button>
                </div>
            </div>
");


            
            #line 103 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\n");


            
            #line 105 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
          
            // Show a page with a list of matching jobs

            if (pager.TotalPageCount == 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div class=\"alert alert-info\">\n                    所选标签内未找到任何作业\n " +
"               </div>\n");


            
            #line 113 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
            }
            else
            {
                if (!(matchingStates is null) && matchingStates.Any())
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div class=\"js-state-list\">\n                        <div clas" +
"s=\"btn-toolbar btn-toolbar-top\">\n");


            
            #line 120 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                             foreach (var matchingState in matchingStates)
                            {
                                var css = state == matchingState.Key ? "btn-primary" : "";

            
            #line default
            #line hidden
WriteLiteral("                                <a role=\"button\" href=\"");


            
            #line 123 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                                  Write(Url.To("/tags/search/" + string.Join(",", tags) + "/" + matchingState.Key));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"js-state-list-command btn btn-sm ");


            
            #line 123 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                                                                                                                                                       Write(css);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 123 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                                                                                                                                                             Write(matchingState.Key);

            
            #line default
            #line hidden
WriteLiteral(" <span class=\"badge\">");


            
            #line 123 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                                                                                                                                                                                                    Write(matchingState.Value);

            
            #line default
            #line hidden
WriteLiteral("</span></a>\n");


            
            #line 124 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\n                    </div>\n");


            
            #line 127 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                }


            
            #line default
            #line hidden
WriteLiteral("                <div class=\"js-jobs-list\">\n\n                    <div class=\"btn-t" +
"oolbar btn-toolbar-top\">\n");


            
            #line 132 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                         if (!IsReadOnly)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <button class=\"js-jobs-list-command btn btn-sm btn-pr" +
"imary\"\n                                    data-url=\"");


            
            #line 135 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                         Write(Url.To("/jobs/enqueued/requeue"));

            
            #line default
            #line hidden
WriteLiteral("\"\n                                    data-loading-text=\"");


            
            #line 136 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                                  Write(Strings.Common_Enqueueing);

            
            #line default
            #line hidden
WriteLiteral("\"\n                                    disabled=\"disabled\">\n                      " +
"          <span class=\"glyphicon glyphicon-repeat\"></span>\n                     " +
"           ");


            
            #line 139 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                           Write(Strings.Common_RequeueJobs);

            
            #line default
            #line hidden
WriteLiteral("\n                            </button>\n");


            
            #line 141 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                        }

            
            #line default
            #line hidden

            
            #line 142 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                         if (!IsReadOnly)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <button class=\"js-jobs-list-command btn btn-sm btn-de" +
"fault\"\n                                    data-url=\"");


            
            #line 145 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                         Write(Url.To("/jobs/enqueued/delete"));

            
            #line default
            #line hidden
WriteLiteral("\"\n                                    data-loading-text=\"");


            
            #line 146 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                                  Write(Strings.Common_Deleting);

            
            #line default
            #line hidden
WriteLiteral("\"\n                                    data-confirm=\"");


            
            #line 147 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                             Write(Strings.Common_DeleteConfirm);

            
            #line default
            #line hidden
WriteLiteral("\"\n                                    disabled=\"disabled\">\n                      " +
"          <span class=\"glyphicon glyphicon-remove\"></span>\n                     " +
"           ");


            
            #line 150 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                           Write(Strings.Common_DeleteSelected);

            
            #line default
            #line hidden
WriteLiteral("\n                            </button>\n");


            
            #line 152 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"

                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");


            
            #line 154 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                   Write(Html.PerPageSelector(pager));

            
            #line default
            #line hidden
WriteLiteral("\n                    </div>\n\n                    <div class=\"table-responsive\">\n " +
"                       <table class=\"table\">\n                            <thead>" +
"\n                                <tr>\n");


            
            #line 161 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                     if (!IsReadOnly)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <th class=\"min-width\">\n                  " +
"                          <input type=\"checkbox\" class=\"js-jobs-list-select-all\"" +
" />\n                                        </th>\n");


            
            #line 166 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    <th class=\"min-width\">");


            
            #line 167 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                                     Write(Strings.Common_Id);

            
            #line default
            #line hidden
WriteLiteral("</th>\n                                    <th>");


            
            #line 168 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                   Write(Strings.Common_Job);

            
            #line default
            #line hidden
WriteLiteral("</th>\n                                    <th class=\"min-width\">");


            
            #line 169 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                                     Write(Strings.Common_State);

            
            #line default
            #line hidden
WriteLiteral("</th>\n                                    <th class=\"min-width\">");


            
            #line 170 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                                     Write(Strings.RecurringJobsPage_Table_LastExecution);

            
            #line default
            #line hidden
WriteLiteral("</th>\n                                    <th class=\"min-width align-right\">");


            
            #line 171 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                                                 Write(Strings.SucceededJobsPage_Table_TotalDuration);

            
            #line default
            #line hidden
WriteLiteral("</th>\n                                </tr>\n                            </thead>\n" +
"                            <tbody>\n");


            
            #line 175 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                 foreach (var job in matchingJobs)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <tr class=\"js-jobs-list-row\">\n");


            
            #line 178 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                         if (!IsReadOnly)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <td>\n                                " +
"                <input type=\"checkbox\" class=\"js-jobs-list-checkbox\" name=\"jobs[" +
"]\" value=\"");


            
            #line 181 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                                                                                                     Write(job.Key);

            
            #line default
            #line hidden
WriteLiteral("\" />\n                                            </td>\n");


            
            #line 183 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                        <td class=\"min-width\">\n                  " +
"                          ");


            
            #line 185 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                       Write(Html.JobIdLink(job.Key));

            
            #line default
            #line hidden
WriteLiteral("\n                                        </td>\n\n");


            
            #line 188 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                         if (job.Value == null)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <td colspan=\"3\">\n                    " +
"                            <em>");


            
            #line 191 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                               Write(Strings.Common_JobExpired);

            
            #line default
            #line hidden
WriteLiteral("</em>\n                                            </td>\n");


            
            #line 193 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                        }
                                        else
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <td class=\"word-break\">\n             " +
"                                   ");


            
            #line 197 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                           Write(Html.JobNameLink(job.Key, job.Value.Job));

            
            #line default
            #line hidden
WriteLiteral("\n                                            </td>\n");



WriteLiteral("                                            <td class=\"min-width\">\n              " +
"                                  ");


            
            #line 200 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                           Write(job.Value.State);

            
            #line default
            #line hidden
WriteLiteral("\n                                            </td>\n");



WriteLiteral("                                            <td class=\"min-width\">\n");


            
            #line 203 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                                 if (job.Value.ResultAt.HasValue)
                                                {
                                                    
            
            #line default
            #line hidden
            
            #line 205 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                               Write(Html.RelativeTime(job.Value.ResultAt.Value));

            
            #line default
            #line hidden
            
            #line 205 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                                                                                
                                                }

            
            #line default
            #line hidden
WriteLiteral("                                            </td>\n");



WriteLiteral("                                            <td class=\"min-width align-right\">\n");


            
            #line 209 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                                  
                                                    var fromDate = job.Value.EnqueueAt ?? job.Value.CreatedAt;
                                                

            
            #line default
            #line hidden

            
            #line 212 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                                 if (fromDate.HasValue && job.Value.ResultAt.HasValue)
                                                {
                                                    
            
            #line default
            #line hidden
            
            #line 214 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                               Write(Html.Raw((job.Value.ResultAt.Value - fromDate.Value).ToString(@"hh\:mm\:ss\.fff")));

            
            #line default
            #line hidden
            
            #line 214 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                                                                                                                       
                                                }

            
            #line default
            #line hidden
WriteLiteral("                                            </td>\n");


            
            #line 217 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </tr>\n");


            
            #line 219 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </tbody>\n                        </table>\n           " +
"         </div>\n                    ");


            
            #line 223 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
               Write(Html.Paginator(pager));

            
            #line default
            #line hidden
WriteLiteral("\n                </div>\n");


            
            #line 225 "..\..\Hangfire.Tags\Dashboard\Pages\TagsJobsPage.cshtml"
            }
        

            
            #line default
            #line hidden
WriteLiteral("    </div>\n</div>\n");


        }
    }
}
#pragma warning restore 1591
